from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DOCUMENT_DIRS: dict[str, str] = {
    "case_reports": "case-report",
    "vulnerability_patterns": "vulnerability-pattern",
    "false_positive_cases": "false-positive-case",
    "component_checklists": "component-checklist",
    "validation_recipes": "validation-recipe",
    "contest_notes": "contest-note",
}

GENERATED_NOTICE = (
    "> Generated by `python -m audit_rag.cli.main export-wiki`. "
    "Do not edit this page by hand; update `data/normalized/` instead."
)


@dataclass(frozen=True)
class ExportedWikiPage:
    document_type: str
    record_id: str
    source_path: str
    output_path: str


@dataclass(frozen=True)
class ExportWikiResult:
    status: str
    wiki_dir: str
    generated_dir: str
    exported_count: int
    pages: list[ExportedWikiPage]

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "wiki_dir": self.wiki_dir,
            "generated_dir": self.generated_dir,
            "exported_count": self.exported_count,
            "pages": [
                {
                    "document_type": page.document_type,
                    "record_id": page.record_id,
                    "source_path": page.source_path,
                    "output_path": page.output_path,
                }
                for page in self.pages
            ],
        }


def export_wiki(root_path: str | Path = ".", wiki_dir: str | Path = "wiki") -> ExportWikiResult:
    """Export normalized JSON records into a read-only Markdown wiki layer."""
    root = Path(root_path)
    wiki_path = root / wiki_dir
    generated_dir = wiki_path / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    pages: list[ExportedWikiPage] = []
    normalized_dir = root / "data" / "normalized"
    for source_dir_name, document_type in DOCUMENT_DIRS.items():
        source_dir = normalized_dir / source_dir_name
        if not source_dir.exists():
            continue
        output_dir = generated_dir / source_dir_name
        output_dir.mkdir(parents=True, exist_ok=True)
        for json_path in sorted(source_dir.glob("*.json")):
            record = _load_json(json_path)
            record_id = str(record.get("id") or record.get("pattern_id") or json_path.stem)
            output_path = output_dir / f"{_slugify(record_id)}.md"
            output_path.write_text(
                _render_record_page(record, document_type, source_dir_name, json_path, root),
                encoding="utf-8",
            )
            pages.append(
                ExportedWikiPage(
                    document_type=document_type,
                    record_id=record_id,
                    source_path=_relpath(json_path, root),
                    output_path=_relpath(output_path, root),
                )
            )

    (generated_dir / "index.md").write_text(_render_generated_index(pages), encoding="utf-8")
    return ExportWikiResult(
        status="ok",
        wiki_dir=_relpath(wiki_path, root),
        generated_dir=_relpath(generated_dir, root),
        exported_count=len(pages),
        pages=pages,
    )


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        msg = f"Expected object JSON in {path}"
        raise ValueError(msg)
    return data


def _render_record_page(
    record: dict[str, Any],
    document_type: str,
    source_dir_name: str,
    json_path: Path,
    root: Path,
) -> str:
    record_id = str(record.get("id") or record.get("pattern_id") or json_path.stem)
    title = _title_for_record(record, record_id)
    lines = [
        f"# {title}",
        "",
        GENERATED_NOTICE,
        "",
        "## Metadata",
        "",
        f"- id: `{record_id}`",
        f"- document_type: `{document_type}`",
        f"- source_json: `{_relpath(json_path, root)}`",
    ]

    for key in ("severity", "category", "language", "component_type", "source_url"):
        value = record.get(key)
        if value:
            lines.append(f"- {key}: {_format_inline(value)}")

    lines.extend(["", "## Summary", ""])
    summary = _summary_for_record(record)
    lines.append(summary if summary else "_No summary-like field found._")

    _append_section(lines, "Broken invariants", record.get("broken_invariants"))
    _append_section(lines, "Tags", record.get("tags"))
    _append_section(lines, "Component types", record.get("component_types"))
    _append_section(lines, "Related case ids", record.get("related_case_ids"))
    _append_section(lines, "Related pattern ids", record.get("related_pattern_ids"))
    _append_section(lines, "Common false positives", record.get("common_false_positives"))
    _append_section(lines, "Validation methods", record.get("validation_methods"))
    _append_section(lines, "Check items", record.get("check_items"))
    _append_section(lines, "Test ideas", record.get("test_ideas"))
    _append_section(lines, "Assertions", record.get("assertions"))
    _append_section(lines, "When it could be real", record.get("when_it_could_be_real"))

    snippets = record.get("snippets")
    if isinstance(snippets, list) and snippets:
        lines.extend(["", "## Source snippets", ""])
        for snippet in snippets[:8]:
            if isinstance(snippet, dict):
                code = snippet.get("code")
                role = snippet.get("role", "snippet")
                note = snippet.get("note")
                if code:
                    lines.append(f"- `{role}`: {code}")
                    if note:
                        lines.append(f"  - note: {note}")

    lines.extend(
        [
            "",
            "## Navigation",
            "",
            "- Generated index: [[generated/index|Generated normalized index]]",
        ]
    )
    if source_dir_name == "false_positive_cases":
        lines.append("- Suggested concept page: [[concepts/soroban-require-auth-false-positives|false-positive / downgrade lessons]]")
    elif "require-auth" in " ".join(_flatten_to_strings(record)).lower():
        lines.append("- Suggested concept page: [[concepts/soroban-require-auth|Soroban require_auth]]")

    lines.append("")
    return "\n".join(lines)


def _render_generated_index(pages: list[ExportedWikiPage]) -> str:
    lines = [
        "# Generated normalized index",
        "",
        GENERATED_NOTICE,
        "",
        f"Exported records: {len(pages)}",
        "",
    ]
    by_type: dict[str, list[ExportedWikiPage]] = {}
    for page in pages:
        by_type.setdefault(page.document_type, []).append(page)
    for document_type in sorted(by_type):
        lines.extend([f"## {document_type}", ""])
        for page in by_type[document_type]:
            link = page.output_path.removeprefix("wiki/").removesuffix(".md")
            lines.append(f"- [[{link}|{page.record_id}]] — `{page.source_path}`")
        lines.append("")
    return "\n".join(lines)


def _title_for_record(record: dict[str, Any], record_id: str) -> str:
    for key in ("finding_title", "name", "issue_claim", "goal", "description", "contest_name"):
        value = record.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return record_id


def _summary_for_record(record: dict[str, Any]) -> str:
    for key in ("summary", "description", "root_cause", "why_not_valid", "goal", "architecture_summary"):
        value = record.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _append_section(lines: list[str], heading: str, value: Any) -> None:
    if value in (None, "", [], {}):
        return
    lines.extend(["", f"## {heading}", ""])
    if isinstance(value, list):
        for item in value:
            lines.append(f"- {_format_inline(item)}")
    elif isinstance(value, dict):
        for key, item in value.items():
            lines.append(f"- {key}: {_format_inline(item)}")
    else:
        lines.append(_format_inline(value))


def _format_inline(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return ", ".join(_format_inline(item) for item in value)
    if isinstance(value, dict):
        return "; ".join(f"{key}={_format_inline(item)}" for key, item in value.items())
    return str(value)


def _flatten_to_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        out: list[str] = []
        for key, item in value.items():
            out.extend(_flatten_to_strings(key))
            out.extend(_flatten_to_strings(item))
        return out
    if isinstance(value, list):
        out = []
        for item in value:
            out.extend(_flatten_to_strings(item))
        return out
    return [str(value)]


def _slugify(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower()).strip("-")
    return slug or "record"


def _relpath(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()
