from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

REPO_ROOT = Path(__file__).resolve().parents[3]
NORMALIZED_DIR = REPO_ROOT / "data" / "normalized"
SCHEMA_DIR = REPO_ROOT / "schemas"

SCHEMA_GLOBS = {
    "case_report.schema.json": "case_reports/*.json",
    "false_positive_case.schema.json": "false_positive_cases/*.json",
    "vulnerability_pattern.schema.json": "vulnerability_patterns/*.json",
    "component_checklist.schema.json": "component_checklists/*.json",
    "validation_recipe.schema.json": "validation_recipes/*.json",
    "contest_note.schema.json": "contest_notes/*.json",
    "low_non_critical_case.schema.json": "low_non_critical_cases/*.json",
}

POLLUTED_TAGS = {
    "high",
    "medium",
    "low",
    "qa",
    "non-critical",
    "ethena",
    "kinetiq",
    "reserve",
    "angle",
    "noya",
    "spectra",
    "dyad",
    "althea",
    "nudgexyz",
    "nudge",
    "nudge.xyz",
    "monetrix",
}

ALLOWED_VALIDATION_STATUSES = {
    "",
    "confirmed-by-sponsor",
    "acknowledged-by-sponsor",
    "confirmed-or-mitigated-in-final-report",
    "disputed-by-sponsor-but-included-in-final-report",
    "confirmed-in-final-report",
    "reported-by-public-audit",
    "public-contest-finding",
    "theory-only",
    "unmitigated-in-mitigation-review",
}

LOCAL_SAMPLE_ID_FILENAME_EXCEPTIONS = {
    "data/normalized/case_reports/reward-debt-desync-case-01.json": "case-reward-debt-desync-01",
    "data/normalized/false_positive_cases/admin-bad-slippage-fp-01.json": "fp-admin-bad-slippage-config-01",
    "data/normalized/vulnerability_patterns/reward-debt-desync-pattern.json": "pattern-reward-debt-desync",
    "data/normalized/component_checklists/reward-distribution-checklist.json": "checklist-reward-distribution",
    "data/normalized/validation_recipes/reward-debt-desync-validation-recipe-01.json": "recipe-reward-debt-desync-01",
}


def _add_violation(violations: list[dict[str, str]], path: Path, message: str) -> None:
    violations.append({"file": str(path.relative_to(REPO_ROOT)), "message": message})


def _load_json(path: Path, violations: list[dict[str, str]]) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - exact JSON errors are implementation detail
        _add_violation(violations, path, f"invalid JSON: {exc}")
        return None


def _validate_schema(violations: list[dict[str, str]]) -> int:
    checked = 0
    for schema_name, file_glob in SCHEMA_GLOBS.items():
        schema_path = SCHEMA_DIR / schema_name
        if not schema_path.exists():
            continue
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        validator = Draft202012Validator(schema)
        for path in sorted(NORMALIZED_DIR.glob(file_glob)):
            data = _load_json(path, violations)
            if data is None:
                continue
            checked += 1
            for error in validator.iter_errors(data):
                _add_violation(violations, path, f"schema: {error.message}")
    return checked


def _check_tags(violations: list[dict[str, str]], path: Path, data: dict[str, Any]) -> None:
    bad_tags = [tag for tag in data.get("tags", []) if str(tag).lower() in POLLUTED_TAGS]
    if bad_tags:
        _add_violation(violations, path, f"tags contain protocol/severity words: {bad_tags}")


def _record_id(data: dict[str, Any]) -> str | None:
    value = data.get("id") or data.get("pattern_id")
    return str(value) if value else None


def _check_id_filename(violations: list[dict[str, str]], path: Path, data: dict[str, Any]) -> None:
    record_id = _record_id(data)
    if not record_id:
        return
    rel = str(path.relative_to(REPO_ROOT))
    if LOCAL_SAMPLE_ID_FILENAME_EXCEPTIONS.get(rel) == record_id:
        return
    if record_id != path.stem:
        _add_violation(violations, path, f"record id '{record_id}' does not match filename '{path.stem}.json'")


def _check_case_report(violations: list[dict[str, str]], path: Path, data: dict[str, Any]) -> None:
    root_cause = data.get("root_cause", "")
    if (
        root_cause.startswith("Report-described")
        or root_cause.startswith("protocol invariant violation in")
        or root_cause.startswith("state/accounting validation gap in")
    ):
        _add_violation(violations, path, "root_cause still uses autogenerated/report-copy prefix")
    invariants = " ".join(data.get("broken_invariants", []))
    if "condition described by" in invariants:
        _add_violation(violations, path, "broken_invariants contain generic condition-described template")
    if "flow should preserve protocol accounting" in invariants:
        _add_violation(violations, path, "broken_invariants contain old generic flow template")
    if not data.get("source_url"):
        _add_violation(violations, path, "case_report missing source_url")
    status = str(data.get("validation_status", ""))
    if status not in ALLOWED_VALIDATION_STATUSES:
        _add_violation(violations, path, f"unknown validation_status: {status}")
    for snippet in data.get("snippets", []) or []:
        if not isinstance(snippet, dict) or snippet.get("role") != "affected-code":
            continue
        code = str(snippet.get("code", ""))
        if "github.com/" in code and "/blob/" not in code:
            _add_violation(violations, path, "affected-code GitHub snippet should use fixed blob permalink")


def _semantic_quality_checks(violations: list[dict[str, str]]) -> None:
    for directory in SCHEMA_GLOBS.values():
        folder = directory.split("/", 1)[0]
        for path in sorted((NORMALIZED_DIR / folder).glob("*.json")):
            data = _load_json(path, violations)
            if data is None:
                continue
            _check_tags(violations, path, data)
            _check_id_filename(violations, path, data)
            if folder == "case_reports":
                _check_case_report(violations, path, data)


def validate_normalized_data() -> dict[str, Any]:
    """Validate JSON schemas plus project-specific RAG quality gates."""

    violations: list[dict[str, str]] = []
    checked = _validate_schema(violations)
    _semantic_quality_checks(violations)
    return {
        "status": "ok" if not violations else "failed",
        "checked_files": checked,
        "violations": violations,
    }
